### ISSUE TITLE
Citations page in addition to references page

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#717]
This is a hard problem to solve with our documentation. We use [Jupyter Book](https://jupyterbook.org/) to create the OG-USA documentation, which is available at [https://pslmodels.github.io/OG-USA/](https://pslmodels.github.io/OG-USA/) and the source code of which is in the [OG-USA/docs/book/](https://github.com/PSLmodels/OG-USA/tree/master/docs/book) directory of the OG-USA repository.

Some past PR broke the compilation of any of the in-text citation references (see broken reference [here](https://pslmodels.github.io/OG-USA/content/theory/intro.html)) or any compilation of the references in the [References section](https://pslmodels.github.io/OG-USA/content/theory/references.html) or in the [Citations section](https://pslmodels.github.io/OG-USA/content/citations.html#) of the documentation. These issues were discussed in Issue #613, and partially solved in subsequent PRs (PR #634 and PR #664). However, it is not clear if the Citations page compilation worked after PR #664 or if it was subsequently broken.

The following is the behavior that I think we want. And I think this will not be straightforward to execute.
1. References page compiles all references cited in the Jupyter Book document, built off of `OGUSA_references.bib` file. PR #683 fixes this. However, PR #683 does not currently address the following two issues.
2. Citations page compiles separately being built off of `citations.bib` file. We want this page to compile a reference line for every reference in `citations.bib`, independent of overlap with `OGUSA_references.bib` and independent of whether any  `citations.bib` references are cited in the text.
3. We want the `citations.bib` file to be able to be scraped the the PSL Models organization for compilation of OG-USA specific references on the PSL Models web page. I think the natural location for `citations.bib` is in the same directory as the main BibTeX file `OGUSA_references.bib`. `citations.bib` is currently at the main level of the OG-USA repo (`OG-USA/citations.bib`).

cc: @jdebacker @MaxGhenis

**Comment by jdebacker** [comment]
@rickecon I hadn't even noticed that the references and citations were not showing up!

I'm glad to see the references are fixed.

> Citations page compiles separately being built off of citations.bib file. We want this page to compile a reference line for every reference in citations.bib, independent of overlap with OGUSA_references.bib and independent of whether any citations.bib references are cited in the text.

Right, this is why [`citations.md`](https://github.com/PSLmodels/OG-USA/blob/master/docs/book/content/citations.md) has the `:all :` statement.  This should produce the above behavior (at least it did for some version of JB - again, not sure what broke and it compiles fine locally for me using JB version 0.9.1.

> We want the citations.bib file to be able to be scraped the the PSL Models organization for compilation of OG-USA specific references on the PSL Models web page. I think the natural location for citations.bib is in the same directory as the main BibTeX file OGUSA_references.bib. citations.bib is currently at the main level of the OG-USA repo (OG-USA/citations.bib).

We do want it to be scraped, which his why it is important this file resides in the top-level directory, since different repos put their docs in different directory structures.  That makes it easy for the scaper to find the file.  This doesn't impact it's compilation in the Jupyter-Book.

**Comment by rickecon** [comment]
@jdebacker. My Juypter Book version is 0.10.0. I wonder if my need in PR #683 to add the `bibtex_bibfiles:` lines is new to v. 0.10.0. We might have to pin the Jupyter Book version to 0.9.1 in the `ogusa-dev` environment until we find a solution.

**Comment by jdebacker** [comment]
Yes, sounds like we missed some updates for JB v 0.10.0...

> I wonder if it will work in version 0.10.0 if we add another reference line to the citations.bib at the bottom of the _config.yml file.

I think trying this would be good.  I'd like to avoid anymore hard pins.  They can cause conflicts with other dependencies.

**Comment by rickecon** [comment]
I changed the `environment.yml` to be `jupyter-book>=0.9.1` in PR #683. However, I still can't get the Citations page to compile under the Jupyter Book 0.10.1 or 0.10.0 versions. I tried the following two fixes with v. 0.10.1 in the `_config.yml` file, neither of which worked:

**Fix attempt 1**
```
bibtex_bibfiles:
   - OGUSA_references.bib
   - ../../citations.bib
```

**Fix attempt 2, copying citations.md to same directory as OGUSA_references.bib**
```
bibtex_bibfiles:
   - OGUSA_references.bib
   - citations.bib
```
I think we should move forward with this PR #683 as it is, and work to fix the citations page in a future PR, leaving this issue thread open until fixed.

**Comment by rickecon** [comment]
I tried updating the `_config.yml` file in the following two ways, both resulting in errors.
**Fix attempt 1**
```
bibtex_bibfiles:
   - [OGUSA_references.bib, ../../citations.bib]
```

**Fix attempt 2, copying citations.md to same directory as OGUSA_references.bib, also adjusting reference in citations.md**
```
bibtex_bibfiles:
   - [OGUSA_references.bib, citations.bib]
```

**Comment by rickecon** [comment]
@jdebacker . I don't know what I did, but the Jupyter Book v. 0.10.1 is now compiling the Citations page, with `citations.bib` not in the `_config.yml` file and located in the main `OG-USA/` directory, and with no changes to `citations.md`. All changes have been incorporated into PR #683. I am closing this issue.
